x-airflow-base: &airflow-base
  build: .                             # construye con nuestro Dockerfile corregido
  user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
  env_file:
    - .env                             # carga GEMINI_API_KEY (y cualquier otra var. secreta)
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    PYTHONPATH: "/opt/airflow/src:${PYTHONPATH}"
  volumes:
    - ./config/airflow.cfg:/opt/airflow/airflow.cfg
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./src:/opt/airflow/src
    - ./config:/opt/airflow/config
    - ./scripts:/opt/airflow/scripts
    - ./exports:/opt/airflow/exports

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:       ${POSTGRES_DB}
    ports:
      - "5432:5432"

  scheduler:
    <<: *airflow-base
    command: ["airflow", "scheduler"]
    restart: always
    depends_on:
      - postgres

  webserver:
    <<: *airflow-base
    command: ["airflow", "webserver"]
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - scheduler
